id: I336B7478
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T09:07:16+00:00'
last_modified: '2022-06-07T12:28:27.884204+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2PD19769
  title: ས་སྐྱའི་ལམ་འབྲས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    DEB3:
      image_group_id: I2PD19932
      title: ''
      total_pages: 688
      order: 1
      base_file: DEB3.txt
    CD85:
      image_group_id: I2PD19933
      title: ''
      total_pages: 472
      order: 2
      base_file: CD85.txt
    20B7:
      image_group_id: I2PD19934
      title: ''
      total_pages: 474
      order: 3
      base_file: 20B7.txt
    A1F4:
      image_group_id: I2PD19935
      title: ''
      total_pages: 516
      order: 4
      base_file: A1F4.txt
    98B5:
      image_group_id: I2PD19936
      title: ''
      total_pages: 450
      order: 5
      base_file: 98B5.txt
    155C:
      image_group_id: I2PD19937
      title: ''
      total_pages: 572
      order: 6
      base_file: 155C.txt
    '9887':
      image_group_id: I2PD19938
      title: ''
      total_pages: 542
      order: 7
      base_file: 9887.txt
    9AA5:
      image_group_id: I2PD19939
      title: ''
      total_pages: 518
      order: 8
      base_file: 9AA5.txt
    '6845':
      image_group_id: I2PD19940
      title: ''
      total_pages: 458
      order: 9
      base_file: 6845.txt
    FDCC:
      image_group_id: I2PD19941
      title: ''
      total_pages: 220
      order: 10
      base_file: FDCC.txt
    '0504':
      image_group_id: I2PD19942
      title: ''
      total_pages: 542
      order: 11
      base_file: 0504.txt
    B1C1:
      image_group_id: I2PD19943
      title: ''
      total_pages: 536
      order: 12
      base_file: B1C1.txt
    9E96:
      image_group_id: I2PD19944
      title: ''
      total_pages: 486
      order: 13
      base_file: 9E96.txt
    '2491':
      image_group_id: I2PD19945
      title: ''
      total_pages: 578
      order: 14
      base_file: 2491.txt
    E17E:
      image_group_id: I2PD19946
      title: ''
      total_pages: 536
      order: 15
      base_file: E17E.txt
    86C8:
      image_group_id: I2PD19947
      title: ''
      total_pages: 470
      order: 16
      base_file: 86C8.txt
    E02E:
      image_group_id: I2PD19948
      title: ''
      total_pages: 498
      order: 17
      base_file: E02E.txt
    E8DB:
      image_group_id: I2PD19949
      title: ''
      total_pages: 368
      order: 18
      base_file: E8DB.txt
    '8786':
      image_group_id: I2PD19950
      title: ''
      total_pages: 542
      order: 19
      base_file: 8786.txt
    BF80:
      image_group_id: I2PD19951
      title: ''
      total_pages: 420
      order: 20
      base_file: BF80.txt
    91F6:
      image_group_id: I2PD19952
      title: ''
      total_pages: 484
      order: 21
      base_file: 91F6.txt
    50D8:
      image_group_id: I2PD19953
      title: ''
      total_pages: 454
      order: 22
      base_file: 50D8.txt
    48EB:
      image_group_id: I2PD19954
      title: ''
      total_pages: 494
      order: 23
      base_file: 48EB.txt
    2D9E:
      image_group_id: I2PD19955
      title: ''
      total_pages: 504
      order: 24
      base_file: 2D9E.txt
    1CFB:
      image_group_id: I2PD19956
      title: ''
      total_pages: 474
      order: 25
      base_file: 1CFB.txt
    1B3B:
      image_group_id: I2PD19957
      title: ''
      total_pages: 510
      order: 26
      base_file: 1B3B.txt
    '4484':
      image_group_id: I2PD19958
      title: ''
      total_pages: 548
      order: 27
      base_file: 4484.txt
    93E4:
      image_group_id: I2PD19959
      title: ''
      total_pages: 480
      order: 28
      base_file: 93E4.txt
    '5251':
      image_group_id: I2PD19960
      title: ''
      total_pages: 538
      order: 29
      base_file: 5251.txt
    67C9:
      image_group_id: I2PD19961
      title: ''
      total_pages: 624
      order: 30
      base_file: 67C9.txt
    DDEF:
      image_group_id: I2PD19962
      title: ''
      total_pages: 450
      order: 31
      base_file: DDEF.txt
    1D4D:
      image_group_id: I2PD19963
      title: ''
      total_pages: 520
      order: 32
      base_file: 1D4D.txt
    '4678':
      image_group_id: I2PD19964
      title: ''
      total_pages: 496
      order: 33
      base_file: 4678.txt
    936E:
      image_group_id: I2PD19965
      title: ''
      total_pages: 402
      order: 34
      base_file: 936E.txt
    2AB8:
      image_group_id: I2PD19966
      title: ''
      total_pages: 538
      order: 35
      base_file: 2AB8.txt
    A4A6:
      image_group_id: I2PD19967
      title: ''
      total_pages: 486
      order: 36
      base_file: A4A6.txt
    DF7C:
      image_group_id: I2PD19968
      title: ''
      total_pages: 498
      order: 37
      base_file: DF7C.txt
    6C14:
      image_group_id: I2PD19969
      title: ''
      total_pages: 466
      order: 38
      base_file: 6C14.txt
    88AF:
      image_group_id: I2PD19970
      title: ''
      total_pages: 518
      order: 39
      base_file: 88AF.txt
    C022:
      image_group_id: I2PD19971
      title: ''
      total_pages: 424
      order: 40
      base_file: C022.txt
    A444:
      image_group_id: I2PD19972
      title: ''
      total_pages: 372
      order: 41
      base_file: A444.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
