id: P000620
initial_creation_type: ocr
source_metadata:
  id: bdr:W2PD19769
  title: ས་སྐྱའི་ལམ་འབྲས།
  author: ''
  volumes:
    d766b91606a749f29613e0340cd4d1e5:
      image_group_id: I2PD19932
      title: ''
      volume_number: 1
      total_pages: 688
    594b9e1753d74a64a1cbd2e3f2cbfcf5:
      image_group_id: I2PD19933
      title: ''
      volume_number: 2
      total_pages: 472
    82fdc5529f7e4262bbffc7b8b4eee25e:
      image_group_id: I2PD19934
      title: ''
      volume_number: 3
      total_pages: 474
    3345fd684f26458fbdd513eb945cba10:
      image_group_id: I2PD19935
      title: ''
      volume_number: 4
      total_pages: 516
    ab4cadff1531452294e02c109ca76fce:
      image_group_id: I2PD19936
      title: ''
      volume_number: 5
      total_pages: 450
    c1b674d4fb5441c3a4388ddf842018b2:
      image_group_id: I2PD19937
      title: ''
      volume_number: 6
      total_pages: 572
    c0d29591c0da41909d88c47fc33e545c:
      image_group_id: I2PD19938
      title: ''
      volume_number: 7
      total_pages: 542
    51e367e8d6ac4a2b8c8fa4d90e5a2013:
      image_group_id: I2PD19939
      title: ''
      volume_number: 8
      total_pages: 518
    52530b8f38c34684b6c74ba17102a289:
      image_group_id: I2PD19940
      title: ''
      volume_number: 9
      total_pages: 458
    b003a3f2e2444aeda939a02db724fd4a:
      image_group_id: I2PD19941
      title: ''
      volume_number: 10
      total_pages: 220
    82b7096b50184d03b82db67e8902ea58:
      image_group_id: I2PD19942
      title: ''
      volume_number: 11
      total_pages: 542
    4e4ff044d5dd418d8090264f0b0e2e7f:
      image_group_id: I2PD19943
      title: ''
      volume_number: 12
      total_pages: 536
    610e8b58966b42a0a4afc12ebe9ffed5:
      image_group_id: I2PD19944
      title: ''
      volume_number: 13
      total_pages: 486
    fe710e16166b43bd93dc4689f62712ee:
      image_group_id: I2PD19945
      title: ''
      volume_number: 14
      total_pages: 578
    8c75f170f47f4ec3a62f6a21b8fa966a:
      image_group_id: I2PD19946
      title: ''
      volume_number: 15
      total_pages: 536
    3bcafa2e3cae4770a9a08de2947da91c:
      image_group_id: I2PD19947
      title: ''
      volume_number: 16
      total_pages: 470
    6daf65f8dc89437ab5eeb2aa34672d1d:
      image_group_id: I2PD19948
      title: ''
      volume_number: 17
      total_pages: 498
    aba27819760b4889ac057253d5b1cbaa:
      image_group_id: I2PD19949
      title: ''
      volume_number: 18
      total_pages: 368
    4c7dafbd923d4b058aa548de835a27dc:
      image_group_id: I2PD19950
      title: ''
      volume_number: 19
      total_pages: 542
    87196033dcb9444c9fd7bc3fbc687efa:
      image_group_id: I2PD19951
      title: ''
      volume_number: 20
      total_pages: 420
    23540a0d410c46b2925d6bb367850a14:
      image_group_id: I2PD19952
      title: ''
      volume_number: 21
      total_pages: 484
    f579ea14e3164410a7a8c2218dce3238:
      image_group_id: I2PD19953
      title: ''
      volume_number: 22
      total_pages: 454
    28a2d9b01f7f498a8cf95e8741b05d78:
      image_group_id: I2PD19954
      title: ''
      volume_number: 23
      total_pages: 494
    7d5880efa70d42e489526924f7220bfb:
      image_group_id: I2PD19955
      title: ''
      volume_number: 24
      total_pages: 504
    b59c2d2d89e645f0bee6489c0c3848fb:
      image_group_id: I2PD19956
      title: ''
      volume_number: 25
      total_pages: 474
    dac2af166c20401da34bf85c3b5f4c47:
      image_group_id: I2PD19957
      title: ''
      volume_number: 26
      total_pages: 510
    d56e3abf320347d795916d0fb9cbfe67:
      image_group_id: I2PD19958
      title: ''
      volume_number: 27
      total_pages: 548
    ec915ec0c74949bc9b72f62b8a1401e7:
      image_group_id: I2PD19959
      title: ''
      volume_number: 28
      total_pages: 480
    bc1847cc44c04f2c83f99f9bbb621a60:
      image_group_id: I2PD19960
      title: ''
      volume_number: 29
      total_pages: 538
    149d6e42c4224d06a555a37ab9ac0214:
      image_group_id: I2PD19961
      title: ''
      volume_number: 30
      total_pages: 624
    f82df0a7416b47309e77db3f5fe43756:
      image_group_id: I2PD19962
      title: ''
      volume_number: 31
      total_pages: 450
    24cc7bf53fa44300951dddefb72c0f96:
      image_group_id: I2PD19963
      title: ''
      volume_number: 32
      total_pages: 520
    35deec3dd13043bbbaccc069a2a1d7a2:
      image_group_id: I2PD19964
      title: ''
      volume_number: 33
      total_pages: 496
    41766e1422dd4ca3856ee5a033d96a7c:
      image_group_id: I2PD19965
      title: ''
      volume_number: 34
      total_pages: 402
    9335e3f23ae443a797a4a834816035ee:
      image_group_id: I2PD19966
      title: ''
      volume_number: 35
      total_pages: 538
    3c5ebc1ec8d248eab28475b8c8930a69:
      image_group_id: I2PD19967
      title: ''
      volume_number: 36
      total_pages: 486
    5888729b38794b1baebe984a0748ee85:
      image_group_id: I2PD19968
      title: ''
      volume_number: 37
      total_pages: 498
    4030d19a64ef40cab5ad8382ed24c20a:
      image_group_id: I2PD19969
      title: ''
      volume_number: 38
      total_pages: 466
    0fbcab4d203946b19a4acf480df1b043:
      image_group_id: I2PD19970
      title: ''
      volume_number: 39
      total_pages: 518
    d871db6656c34913b2d42076c2f07770:
      image_group_id: I2PD19971
      title: ''
      volume_number: 40
      total_pages: 424
    fec0b47f4d834545afe7c3f35eb66c82:
      image_group_id: I2PD19972
      title: ''
      volume_number: 41
      total_pages: 372
